# Q1. What is the difference between Ordinal Encoding and Label Encoding? Provide an example of when you might choose one over the other.

---> Ordinal encoding is used when the categorical data has an inherent order or hierarchy, while label encoding is used when the categorical data has no inherent order or hierarchy.

---> For example if dataset comntains size of shirts (small, medium, large) we will use ordinal encoding as there is inherent order (small < medium < large). But if we have dataset of color (red, blue, green) then we use label encoding as it is not in any order.

# Q2. Explain how Target Guided Ordinal Encoding works and provide an example of when you might use it in a machine learning project.

---> Steps involved in target ordinal encoding are

1) Choose a categorical variable.
2) Take the aggregated mean of the categorical variable and apply it to the target variable.
3) Sort the values of the categorical variable based on the aggregated mean.
4) Assign an ordinal number to each unique category based on its rank.

---> An example when I might use Target guided ordinal encoding is a dataset of cities and price of land corresponding to those cities.

# Q3. Define covariance and explain why it is important in statistical analysis. How is covariance calculated?

---> Covariance is a statistical tool used to determine the relationship between the movements of two random variables.

---> It measures the joint variability of two random variables and can take any positive or negative value.

--->  A positive covariance means that the two variables tend to move in the same direction, while a negative covariance means that they move in opposite directions.

---> It is used to identify trends and patterns in data and can help us make predictions about future outcomes.

---> Formula of covariance is:
        cov(X,Y) = E[(X - E[X])(Y - E[Y])]
        
---> where X and Y are random variables, and E[X] and E[Y] are their expected values

# Q4. For a dataset with the following categorical variables: Color (red, green, blue), Size (small, medium, large), and Material (wood, metal, plastic), perform label encoding using Python's scikit-learn library. Show your code and explain the output.

In [3]:
from sklearn.preprocessing import LabelEncoder

df = {'Color': ['red', 'green', 'blue', 'green', 'blue'],
        'Size': ['small', 'medium', 'large', 'medium', 'small'],
        'Material': ['wood', 'metal', 'plastic', 'metal', 'wood']}

le = LabelEncoder()

for col in df:
    df[col] = le.fit_transform(df[col])
    
df

{'Color': array([2, 1, 0, 1, 0]),
 'Size': array([2, 1, 0, 1, 2]),
 'Material': array([2, 0, 1, 0, 2])}

# Q5. Calculate the covariance matrix for the following variables in a dataset: Age, Income, and Education level. Interpret the results.

In [4]:
import numpy as np

# Create a sample dataset
data = np.array([[25, 50000, 12],
                 [30, 60000, 16],
                 [35, 70000, 18]])

cov_matrix = np.cov(data.T)

print(cov_matrix)

[[2.50000000e+01 5.00000000e+04 1.50000000e+01]
 [5.00000000e+04 1.00000000e+08 3.00000000e+04]
 [1.50000000e+01 3.00000000e+04 9.33333333e+00]]


# Q6. You are working on a machine learning project with a dataset containing several categorical variables, including "Gender" (Male/Female), "Education Level" (High School/Bachelor's/Master's/PhD), and "Employment Status" (Unemployed/Part-Time/Full-Time). Which encoding method would you use for each variable, and why?

---> Gender : Since there are only 2 catagories, so I can use binary encoding.

---> Education Level : There are multiple variables so I can use one hot encoding, which involves creating a new column for each catagory.

---> Employment status : I can use one hot encoding or ordinal encoding as there are multiple catagorical variables.


# Q7. You are analyzing a dataset with two continuous variables, "Temperature" and "Humidity", and two categorical variables, "Weather Condition" (Sunny/Cloudy/Rainy) and "Wind Direction" (North/South/ East/West). Calculate the covariance between each pair of variables and interpret the results.

In [ ]:
import numpy as np

# Create a sample dataset
data1 = np.array([[25, 60, 'Sunny', 'North'],
                 [30, 70, 'Cloudy', 'South'],
                 [35, 80, 'Rainy', 'East']])


continuous_data = data1[:, :2]

cov_matrix1 = np.cov(continuous_data.T)

print(cov_matrix1)